# Generated by Django 4.2 on 2023-06-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='productdb',
        ),
    ]
