# Generated by Django 4.2 on 2023-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_product_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='catname',
            new_name='categoryname',
        ),
        migrations.AddField(
            model_name='productdb',
            name='productname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
