# Generated by Django 4.2 on 2023-06-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_rename_catname_productdb_categoryname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='categoryname',
            new_name='category',
        ),
    ]
