# Generated by Django 4.2 on 2023-06-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_prodb_delete_productsdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prodb',
            new_name='productdb',
        ),
    ]
