# Generated by Django 4.2 on 2023-06-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_prodb_productdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productdb',
            new_name='productdata',
        ),
    ]
