# Generated by Django 4.2 on 2023-06-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_rename_productdb_productdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='image',
            new_name='productimage',
        ),
    ]
