# Generated by Django 4.2 on 2023-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_rename_image_productdata_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='productimage',
        ),
        migrations.AddField(
            model_name='productdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
